# kustomize/overlays/development/patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: rails-app
        image: itssam509/rails-app:dev
