resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - statefulset.yaml
  - pv.yaml
  - pvc.yaml
  - service-account.yaml
  - role-binding.yaml
  - ingress.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
  - logging/fluentd.yaml
  - logging/elasticsearch.yaml
  - logging/kibana.yaml
          
