apiVersion: v1
kind: Service
metadata:
  name: rails-app
spec:
  type: NodePort # or LoadBalancer for external access
  selector:
    app: rails-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007  # Optional, Kubernetes will assign a port if not specified
